// Generated by `bun run generate:lens-calibration` from via-coordinate-map.csv.
// Do not edit this file directly.
export const BISCUIT_BOARD_LENS_CALIBRATION_MODEL = {
  kind: "piecewise-linear-delaunay",
  extrapolation: "convex-hull-affine",
  extrapolationJacobian: [
    1.0227930569234953, 0.013047276263398149, -0.025904175417893027,
    1.0200524772248667,
  ],
  controlPoints: [
    [-31.5, 21.5, 51.400002, 94.699997],
    [-31.5, -21.5, 51, 49.700001],
    [10.75, 23.5, 97.199997, 96.199997],
    [32.5, 22, 117.2, 92.300003],
    [-2, 2, 81.800003, 74],
    [-14, -6, 69.277, 65.712273],
    [32.5, -22, 116.8, 50.700001],
    [-18, 6, 65.199997, 78.300003],
    [26.75, 19.5, 109.32521, 91.852798],
    [-23.5, 21.5, 59.615, 94.621],
    [-2, -6, 81.724, 65.537],
    [32.5, 10, 116.9, 79.8],
    [32.5, -6, 116.8, 63.1],
    [-18, -2, 65.105, 69.903],
    [-10, 2, 73.4, 74],
  ],
  triangles: [
    [0, 1, 13],
    [0, 2, 9],
    [0, 7, 9],
    [0, 7, 13],
    [1, 5, 10],
    [1, 5, 13],
    [1, 6, 10],
    [2, 3, 8],
    [2, 4, 8],
    [2, 4, 14],
    [2, 9, 14],
    [3, 8, 11],
    [4, 8, 11],
    [4, 10, 12],
    [4, 10, 14],
    [4, 11, 12],
    [5, 10, 14],
    [5, 13, 14],
    [6, 10, 12],
    [7, 9, 14],
    [7, 13, 14],
  ],
  hullEdges: [
    [0, 1],
    [0, 2],
    [1, 6],
    [2, 3],
    [3, 11],
    [6, 12],
    [11, 12],
  ],
} as const

/** @deprecated Bilinear baseline retained for API compatibility; the export uses the piecewise-linear model. */
export const BISCUIT_BOARD_LENS_CALIBRATION_MATRIX = [
  [
    83.63608391744732, 1.023284902399703, 0.013358773179639016,
    -0.00013166409170850118,
  ],
  [
    71.6845727295304, -0.02191052027901032, 1.0225817497717664,
    -0.0010690775902058825,
  ],
] as const

export const BISCUIT_BOARD_LENS_CALIBRATION_FIT = {
  transform: "piecewise-linear-delaunay",
  extrapolation: "convex-hull-affine",
  triangleCount: 21,
  hullEdgeCount: 7,
  sourcePointCount: 15,
  includedViaNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
  excludedViaNumbers: [],
  rmsError: 0,
  maxResidualError: 0,
  leaveOneOutRmsError: 1.7977273012661898,
  baselineBilinearRmsError: 1.136868300954825,
} as const
