// Generated by `bun run generate:lens-calibration` from via-coordinate-map.csv.
// Do not edit this file directly.
export const BISCUIT_BOARD_LENS_CALIBRATION_MATRIX = [
  [
    83.65980006195808, 1.0221134297130683, 0.016303536111300976,
    -0.0002240949113389866,
  ],
  [
    71.69211041573234, -0.022282848652282874, 1.0235176817866805,
    -0.0010984548152200868,
  ],
] as const

export const BISCUIT_BOARD_LENS_CALIBRATION_FIT = {
  sourcePointCount: 15,
  includedViaNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15],
  excludedViaNumbers: [10],
  rmsError: 1.1714061202856103,
  maxResidualError: 2.4290264185902553,
} as const
