import { resolve } from "node:path"
import { deriveLensCalibrationFromCsv } from "../lib/coordinate_map/derive-lens-calibration"

const csvPath = resolve(
  import.meta.dir,
  "../lib/coordinate_map/via-coordinate-map.csv",
)
const outputPath = resolve(
  import.meta.dir,
  "../lib/coordinate_map/lens-calibration-generated.ts",
)
const fit = deriveLensCalibrationFromCsv(await Bun.file(csvPath).text())
const [xRow, yRow] = fit.matrix
const formatMatrixRow = (row: number[]) => `  [
    ${row.slice(0, 3).join(", ")},
    ${row[3]},
  ]`

const output = `// Generated by \`bun run generate:lens-calibration\` from via-coordinate-map.csv.
// Do not edit this file directly.
export const BISCUIT_BOARD_LENS_CALIBRATION_MATRIX = [
${formatMatrixRow(xRow)},
${formatMatrixRow(yRow)},
] as const

export const BISCUIT_BOARD_LENS_CALIBRATION_FIT = {
  sourcePointCount: ${fit.sourcePointCount},
  includedViaNumbers: [${fit.includedViaNumbers.join(", ")}],
  excludedViaNumbers: [${fit.excludedViaNumbers.join(", ")}],
  rmsError: ${fit.rmsError},
  maxResidualError: ${fit.maxResidualError},
} as const
`

await Bun.write(outputPath, output)

console.log(
  `Generated lens calibration from ${fit.includedViaNumbers.length}/${fit.sourcePointCount} points (RMS ${fit.rmsError.toFixed(4)}); excluded vias: ${fit.excludedViaNumbers.join(", ") || "none"}`,
)
