import { resolve } from "node:path"
import { deriveLensCalibrationFromCsv } from "../lib/coordinate_map/derive-lens-calibration"

const csvPath = resolve(
  import.meta.dir,
  "../lib/coordinate_map/via-coordinate-map.csv",
)
const outputPath = resolve(
  import.meta.dir,
  "../lib/coordinate_map/lens-calibration-generated.ts",
)
const fit = deriveLensCalibrationFromCsv(await Bun.file(csvPath).text())
const [xRow, yRow] = fit.matrix
const model = fit.model

const formatNumberArray = (values: readonly number[]) =>
  `[${values.join(", ")}]`
const formatControlPoints = (points: readonly (readonly number[])[]) =>
  points.map((point) => `    ${formatNumberArray(point)},`).join("\n")

const output = `// Generated by \`bun run generate:lens-calibration\` from via-coordinate-map.csv.
// Do not edit this file directly.
export const BISCUIT_BOARD_LENS_CALIBRATION_MODEL = {
  kind: "${model.kind}",
  extrapolation: "${model.extrapolation}",
  extrapolationJacobian: ${formatNumberArray(model.extrapolationJacobian)},
  controlPoints: [
${formatControlPoints(model.controlPoints)}
  ],
  triangles: [
${formatControlPoints(model.triangles)}
  ],
  hullEdges: [
${formatControlPoints(model.hullEdges)}
  ],
} as const

/** @deprecated Bilinear baseline retained for API compatibility; the export uses the piecewise-linear model. */
export const BISCUIT_BOARD_LENS_CALIBRATION_MATRIX = [
  ${formatNumberArray(xRow)},
  ${formatNumberArray(yRow)},
] as const

export const BISCUIT_BOARD_LENS_CALIBRATION_FIT = {
  transform: "${model.kind}",
  extrapolation: "${model.extrapolation}",
  triangleCount: ${model.triangles.length},
  hullEdgeCount: ${model.hullEdges.length},
  sourcePointCount: ${fit.sourcePointCount},
  includedViaNumbers: [${fit.includedViaNumbers.join(", ")}],
  excludedViaNumbers: [${fit.excludedViaNumbers.join(", ")}],
  rmsError: ${fit.rmsError},
  maxResidualError: ${fit.maxResidualError},
  leaveOneOutRmsError: ${fit.leaveOneOutRmsError},
  baselineBilinearRmsError: ${fit.baselineBilinearRmsError},
} as const
`

await Bun.write(outputPath, output)
const formatResult = Bun.spawnSync([
  "bunx",
  "@biomejs/biome",
  "format",
  "--write",
  outputPath,
])
if (formatResult.exitCode !== 0) {
  throw new Error(formatResult.stderr.toString())
}

console.log(
  `Generated ${model.kind} lens calibration with ${model.triangles.length} triangles from ${fit.includedViaNumbers.length}/${fit.sourcePointCount} points (RMS ${fit.rmsError.toExponential(2)}, bilinear baseline ${fit.baselineBilinearRmsError.toFixed(4)})`,
)
